### ISSUE TITLE
虚拟定位这里可以考虑加上随机偏移

### ISSUE THREAD

**Issue by iola1999** [sky-wei/xposed-rimet#15]
https://github.com/sky-wei/xposed-rimet/blob/5f9f536471bd4a156506b4222465418655b47a34/app/src/main/java/com/sky/xposed/rimet/plugin/dingding/DingDingHandler.java#L354-L356

经纬度随机偏移 0.00003～0.00015，我认为这样也许会比较安全。不清楚钉钉为何没做这样的检测来防作弊。

**Comment by anysoft** [comment]
可以自己fork之后 提交request pull 让作者合并呗。其实还可以加wifi列表虚拟
