### ISSUE TITLE
钉钉特征码自效验问题

### ISSUE THREAD

**Issue by Cross2pro** [sky-wei/xposed-rimet#23]
`    private static Signature[] getRawSignature(Context paramContext, String paramString) {
        if (paramString == null || paramString.length() == 0 || paramContext == null) {
            return null;
        }
        try {
            PackageInfo localPackageInfo = paramContext.getPackageManager().getPackageInfo(paramString, 64);
            if (localPackageInfo != null) {
                return localPackageInfo.signatures;
            }
            return null;
        } catch (PackageManager.NameNotFoundException e) {
            return null;
        }
    }`
如上
钉钉会进行特征码自效验，返回Signature数组，猜测这也就是很多功能无法使用的原因之一。建议修复这个补丁，进行hook

**Comment by qq1091192337** [comment]
这个类在package com.android.dingtalk.share.ddsharemodule.plugin;
