### ISSUE TITLE
请问编译的时候  报错如下怎样解决呢

### ISSUE THREAD

**Issue by shuaisheng** [sky-wei/xposed-rimet#4]
> Could not get unknown property 'storePassword' for project ':app' of type org.gradle.api.Project.

**Comment by shuaisheng** [comment]
已解决

**Comment by zhaoxilingcheng** [comment]
> Could not get unknown property 'storePassword' for project ':app' of type org.gradle.api.Project.

哥怎么解决的，我安卓超菜

**Comment by qq1091192337** [comment]
> > Could not get unknown property 'storePassword' for project ':app' of type org.gradle.api.Project.
> 
> 哥怎么解决的，我安卓超菜

删了那一段StorePassword就完了呗
