### ISSUE TITLE
一加七pro master 分支的虚拟定位不能用

### ISSUE THREAD

**Issue by shuaisheng** [sky-wei/xposed-rimet#5]
输入 位置点击搜索没有反应

**Comment by shuaisheng** [comment]
已解决

**Comment by cscectc** [comment]
请问你用的助手版本和钉钉版本是多少了？谢谢

**Comment by zhaoxilingcheng** [comment]
> 请问你用的助手版本和钉钉版本是多少了？谢谢

我是前天开始不能用的

**Comment by cscectc** [comment]
> > 请问你用的助手版本和钉钉版本是多少了？谢谢
> 
> 我是前天开始不能用的

助手是1.2.5的时候还能用，助手升到1.2.6时钉钉版本4.6.37能用，我看新版助手支持钉钉4.7.0了，我就都升级了，刚开始能用，后来想用了发现设置里没有钉钉助手了，重新安装了太极、钉钉助手1.2.6、钉钉4.7.0后设置里还是没有看到钉钉助手

**Comment by zhaoxilingcheng** [comment]
> > > 请问你用的助手版本和钉钉版本是多少了？谢谢
> > 
> > 
> > 我是前天开始不能用的
> 
> 助手是1.2.5的时候还能用，助手升到1.2.6时钉钉版本4.6.37能用，我看新版助手支持钉钉4.7.0了，我就都升级了，刚开始能用，后来想用了发现设置里没有钉钉助手了，重新安装了太极、钉钉助手1.2.6、钉钉4.7.0后设置里还是没有看到钉钉助手

是的，我现在也没法用了。

**Comment by ziwux** [comment]
> > > > 请问你用的助手版本和钉钉版本是多少了？谢谢
> > > 
> > > 
> > > 我是前天开始不能用的
> > 
> > 
> > 助手是1.2.5的时候还能用，助手升到1.2.6时钉钉版本4.6.37能用，我看新版助手支持钉钉4.7.0了，我就都升级了，刚开始能用，后来想用了发现设置里没有钉钉助手了，重新安装了太极，钉钉助手1.2.6，钉钉4.7.0后设置里还是没有看到钉钉助手
> 
> 是的，我现在也没法用了。

等待作者修复更新吧！

**Comment by zhaoxilingcheng** [comment]
> > > > > 请问你用的助手版本和钉钉版本是多少了？谢谢
> > > > 
> > > > 
> > > > 我是前天开始不能用的
> > > 
> > > 
> > > 助手是1.2.5的时候还能用，助手升到1.2.6时钉钉版本4.6.37能用，我看新版助手支持钉钉4.7.0了，我就都升级了，刚开始能用，后来想用了发现设置里没有钉钉助手了，重新安装了太极，钉钉助手1.2.6，钉钉4.7.0后设置里还是没有看到钉钉助手
> > 
> > 
> > 是的，我现在也没法用了。
> 
> 等待作者修复更新吧！

你会安卓吗？我这没法编译，好烦

**Comment by ziwux** [comment]
> > > > > > 请问你用的助手版本和钉钉版本是多少了？谢谢
> > > > > 
> > > > > 
> > > > > 我是前天开始不能用的
> > > > 
> > > > 
> > > > 助手是1.2.5的时候还能用，助手升到1.2.6时钉钉版本4.6.37能用，我看新版助手支持钉钉4.7.0了，我就都升级了，刚开始能用，后来想用了发现设置里没有钉钉助手了，重新安装了太极，钉钉助手1.2.6，钉钉4.7.0后设置里还是没有看到钉钉助手
> > > 
> > > 
> > > 是的，我现在也没法用了。
> > 
> > 
> > 等待作者修复更新吧！
> 
> 你会安卓吗？我这没法编译，好烦

不会

**Comment by ziwux** [comment]
> > > > > > > 请问你用的助手版本和钉钉版本是多少了？谢谢
> > > > > > 
> > > > > > 
> > > > > > 我是前天开始不能用的
> > > > > 
> > > > > 
> > > > > 助手是1.2.5的时候还能用，助手升到1.2.6时钉钉版本4.6.37能用，我看新版助手支持钉钉4.7.0了，我就都升级了，刚开始能用，后来想用了发现设置里没有钉钉助手了，重新安装了太极，钉钉助手1.2.6，钉钉4.7.0后设置里还是没有看到钉钉助手
> > > > 
> > > > 
> > > > 是的，我现在也没法用了。
> > > 
> > > 
> > > 等待作者修复更新吧！
> > 
> > 
> > 你会安卓吗？我这没法编译，好烦
> 
> 不会

我不太懂这个，没有最新版的源码，编译出来有用吗？

**Comment by zhaoxilingcheng** [comment]
> > > > > > > > 请问你用的助手版本和钉钉版本是多少了？谢谢
> > > > > > > 
> > > > > > > 
> > > > > > > 我是前天开始不能用的
> > > > > > 
> > > > > > 
> > > > > > 助手是1.2.5的时候还能用，助手升到1.2.6时钉钉版本4.6.37能用，我看新版助手支持钉钉4.7.0了，我就都升级了，刚开始能用，后来想用了发现设置里没有钉钉助手了，重新安装了太极，钉钉助手1.2.6，钉钉4.7.0后设置里还是没有看到钉钉助手
> > > > > 
> > > > > 
> > > > > 是的，我现在也没法用了。
> > > > 
> > > > 
> > > > 等待作者修复更新吧！
> > > 
> > > 
> > > 你会安卓吗？我这没法编译，好烦
> > 
> > 
> > 不会
> 
> 我不太懂这个，没有最新版的源码，编译出来有用吗？

还有别的可以用的
