### ISSUE TITLE
请问最新版本是1.4.1的啊，我怎么在52上看到1.4.4的啊  我试了安装签名不一致没敢装

### ISSUE THREAD

**Issue by wangyuan0217** [sky-wei/xposed-rimet#66]
![image](https://user-images.githubusercontent.com/12730214/187068362-e3baccbd-96ee-4c3d-8ce8-c44028cb86e4.png)

https://www.52pojie.cn/thread-1680154-5-1.html

**Comment by guation** [comment]
其他人做的适配高版本所以使用了自己的签名

**Comment by hais-hbh** [comment]
我试了1.4.4的版本，防撤回还是不生效
